name: Bun.sh CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: cp patches/bun_duckdb.js node_modules/@duckdb/node-bindings/duckdb.js
    - run: bun build ./hepop.js --compile --outfile hepop

